export const playing = state => state.playing;
export const fullScreen = state => state.fullScreen;
export const playList = state => state.playList;
export const sequenceList = state => state.sequenceList;
export const mode = state => state.mode;
export const currentIndex = state => state.currentIndex;
export const currentSong = state => {
  return state.playList[state.currentIndex] || {};
};
export const showFooter = state => state.showFooter;
export const transitionName = state => state.transitionName;
export const query = state => state.query;
export const searchHistory = state => state.searchHistory;
export const playHistory = state => state.playHistory;
export const favoriteList = state => state.favoriteList;
export const userInfo = state => state.userInfo;
export const isLogin = state => !!state.userInfo;
export const showTips = state => state.showTips;
export const tipText = state => state.tipText;
export const loading = state => state.loading;
